# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Toolchest Docs
site_url: "https://trytoolchest.com"
theme:
  name: material
  icon:
    logo: material/wrench
    repo: fontawesome/brands/github
  favicon: images/toolchest_t.png
  features:
    - navigation.tabs
    - header.autohide
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: white

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
nav:
  - Home: "index.md"
  - Getting Started:
      - Installation: "getting-started/installation.md"
      - Running Bioinformatics Packages with Toolchest: "getting-started/running-bioinformatics-on-toolchest.md"
      - Custom Python Functions and Containers: "getting-started/python-functions-and-containers.md"
      - Using Files: "getting-started/using-files.md"
  - Tool Reference:
      - About the Tool Reference: "tool-reference/about.md"
      - Aligners:
          - About Aligners: "tool-reference/aligners.md"
          - Bowtie 2: "tool-reference/aligners/bowtie-2.md"
          - Clustal Omega: "tool-reference/aligners/clustal-omega.md"
          - Diamond:
              - About diamond: "tool-reference/aligners/diamond.md"
              - DIAMOND BLASTP: "tool-reference/aligners/diamond/diamond-blastp.md"
              - DIAMOND BLASTX: "tool-reference/aligners/diamond/diamond-blastx.md"
          - Kallisto: "tool-reference/aligners/kallisto.md"
          - RAPSearch2: "tool-reference/aligners/rapsearch2.md"
          - Salmon: "tool-reference/aligners/salmon.md"
          - STAR: "tool-reference/aligners/star.md"
      - Assemblers:
          - About Assemblers: "tool-reference/assemblers.md"
          - MEGAHIT: "tool-reference/assemblers/megahit.md"
          - Unicycler: "tool-reference/assemblers/unicycler.md"
      - Demultiplexers:
          - About Demultiplexers: "tool-reference/demultiplexers.md"
          - DEMUCS: "tool-reference/demultiplexers/demucs.md"
      - Structure Prediction:
          - About Structure Prediction: "tool-reference/structure-prediction.md"
          - AlphaFold: "tool-reference/structure-prediction/alphafold.md"
      - Taxonomic Classifiers:
          - About Taxonomic Classifiers: "tool-reference/taxonomic-classifiers.md"
          - Centrifuge: "tool-reference/taxonomic-classifiers/centrifuge.md"
          - Kraken 2: "tool-reference/taxonomic-classifiers/kraken-2.md"
          - MetaPhlAn: "tool-reference/taxonomic-classifiers/metaphlan.md"
      - Workflows / Meta-Tools:
            - About Workflows / Meta-Tools: "tool-reference/workflows-meta-tools.md"
            - HUMAnN 3: "tool-reference/workflows-meta-tools/humann3.md"
      - Pre-Processing:
          - About Pre-Processing: "tool-reference/pre-processing.md"
          - FastQC: "tool-reference/pre-processing/fastqc.md"
      - Post-processing:
          - About Post-Processing: "tool-reference/post-processing.md"
          - Bracken: "tool-reference/post-processing/bracken.md"
      - Python 3: "tool-reference/python3.md"
      - Test Runs: "tool-reference/test-runs.md"
      - Transfer: "tool-reference/transfer.md"
      - All Other Tools: "tool-reference/all-other-tools.md"
  - Feature Reference:
      - Adding and Updating Custom Databases: "feature-reference/adding-and-updating-custom-databases.md"
      - Asynchronous Runs: "feature-reference/async-runs.md"
      - Authentication: "feature-reference/authentication.md"
      - The Toolchest Output Object: "feature-reference/output-objects.md"
      - Using AWS with Toolchest: "feature-reference/using-aws-with-toolchest.md"
  - Toolchest Hosted Cloud:
      - Instance Types: "toolchest-hosted-cloud/instance-types.md"
      - Pricing: "toolchest-hosted-cloud/pricing.md"
      - Running Toolchest in Your AWS Account: "toolchest-hosted-cloud/running-toolchest-in-your-aws-account.md"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trytoolchest/lug
  analytics:
    provider: google
    property: G-END20F9GDJ
  generator: false
repo_url: https://github.com/trytoolchest/toolchest-client-python
repo_name: toolchest-client-python
edit_uri: edit/main/docs/docs
copyright: Copyright 2022 Toolchest, Inc.
